baseURL = ""
languageCode = "en-us"
title = "lafx0"
theme = "hugo-coder"

[params]
    author = "Sulejman Bijedic"
    info = "Penetration Tester, eCPPT"
    description = "Write-ups about Linux and Security"
    keywords = "blog,security,linux"
    avatarurl = "images/avatar_profile.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "'  '"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]



    # Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/info/"


    # Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mrlafxo/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/lafx01/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/sulejmanbijedic/"
